### ISSUE TITLE
Mobile menu does not stay closed when moving from page to page

### ISSUE THREAD

**Issue by K20shores** [NCAR/music-box-interactive-client#160]
**Describe the bug**
When on a mobile view, the layout menu will rexpand when moving to a different page.

**To Reproduce**

1. Checkout the `main` branch
2. Open the site on a browser window sized for a mobile device
3. Close the sidebar navigation
4. Click on get started
5. The sidebar will reappear

**Expected behavior**
The side bar stays hidden when moving to a new page

**Screenshots**

![Screenshot 2023-12-11 at 12 25 07 PM](https://github.com/NCAR/music-box-interactive-client/assets/13836216/732ee243-b321-491c-a1e5-2a9f961187c3)

![Screenshot 2023-12-11 at 12 25 13 PM](https://github.com/NCAR/music-box-interactive-client/assets/13836216/bf5f420c-38e8-4c72-941b-19397fee8138)

![Screenshot 2023-12-11 at 12 25 20 PM](https://github.com/NCAR/music-box-interactive-client/assets/13836216/638a2c34-b4f9-4175-bbfb-8f8c4981fa36)

**Comment by Sky-De** [comment]
@K20shores Hello there! Before I proceed with fixing the issue you reported, I just need to confirm whether it's alright for the sidebar to be closed by default on both mobile and desktop. If that's the case, I've already taken care of it by setting menuIsOpen to false. On the other hand, if you need the sidebar to be open by default on desktop, or closed on mobile and open on desktop, we might need to create a custom hook to keep track of screen size changes to address this issue. If the first solution works for you, please let me know so I can create a pull request. Otherwise, we may need to discuss the best approach for this issue, which could involve some significant changes to your application in terms of best practices.
thanks,SkyDe

**Comment by K20shores** [comment]
@Sky-De we need the sidebar to be open by default on desktop, and closed by default on mobile. It would be nice if the closing happened automatically.

This used to work for use when our frontend was in vanilla html and css and we used bootstrap. Now we use react-bootstrap and react, but I know that bootstrap has some components that are [responsive by default](https://react-bootstrap.netlify.app/docs/components/navbar/#responsive-behaviors). Perhaps they could help resolve this?

Either way, if you can provide a solution which is open by default on desktop and closed by default on mobile we will happily accept the contribution, regardless of the implementation.
