### ISSUE TITLE
Cannot remove row in evolving conditions table.

### ISSUE THREAD

**Issue by K20shores** [NCAR/music-box-interactive-client#280]
**Describe the bug**
First reported by @SancyW in #243. Rows in the evolving conditions table aren't properly removed. When you're on the first page of the table, the row you delete is properly removed. When you are on any other page of the table, you click on an x and items from the table are removed, but not the row you clicked on.

**To Reproduce**

1. Go to [https://musicbox.acom.ucar.edu/](https://musicbox.acom.ucar.edu/)
2. Click on Get Started
3. Click on Select Example
4. Click on the Chapman example
5. In the left side bar, click on Conditions
6. Click on the Evolving tab
7. Remove the first row, observe that it disappears 
8. Scroll down and click on any other page of the table data
9. Scroll back up and try to remove the second row
10. The second row will become the first on this page. It seems like the delete button doesn't properly work with page data

**Expected behavior**
The remove row button works with paged data

**Comment by SancyW** [comment]
Yes, it cannot be deleted. 
However, I suggest using another example to test, replacing the Chapman cycle with the Full Gas-Phase Mechanism because all values ​​equal zero in the Chapman cycle, making it difficult to distinguish whether they are deleted.
Here's the file.
[evolving conditions.csv](https://github.com/NCAR/music-box-interactive-client/files/15078689/evolving.conditions.csv)
